### ISSUE TITLE
Clean up and homogenize scripts code

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-scripts#141]
### Part 1

- [x] Split scripts into load, convert and store steps. Name them all "px:foo.convert" and not "px:foo-convert".
- [ ] Homogenize names of ports of component steps. E.g. "source.fileset" and "source.in-memory" and not "fileset.in" and "in-memory.in".
- [ ] Possibly convert single-document ports and even anyFileURI options to fileset + in-memory ports.
- [ ] Merge fileset and in-memory ports into a single port, where the first document would be the fileset and the rest the in-memory documents.

### Part 2

- [ ] Add input validation to all scripts (to load steps): https://github.com/daisy/pipeline-scripts/issues/112. There should be an option named "validation" with possible values "off", "report" and "abort" (see https://github.com/daisy/pipeline-scripts/issues/111).
- [ ] Give all scripts a "status" output port with a `d:status` document (for now `d:validation-status`, see https://github.com/daisy/pipeline-framework/issues/121). 
- [ ] Give all store steps an output port with a `c:result` document.
- [ ] Make sure all scripts have media-type set on all inputs, outputs and options (https://github.com/daisy/pipeline-tasks/issues/105)

**Comment by bertfrees** [comment]
@rdeltour @josteinaj Thoughts?

**Comment by josteinaj** [comment]
Ok, yeah it makes sense.

Merging the fileset and in-memory ports would be nice. It would make it easier to connect steps, while in every step you'd start and end with some step to split/combine the fileset and in-memory parts. Maybe `px:fileset-join` could be extended and reused for the result and a new `px:fileset-read` could be created for reading the fileset and in-memory parts. This could be gradually introduced script-by-script, it doesn't have to be a big refactoring.

**Comment by bertfrees** [comment]
My idea was to combine the ports even in the fileset utility steps, so that normally you wouldn't even have to split/merge the sequences in the higher-level steps.

**Comment by rdeltour** [comment]
Cleaning and harmonizing as you suggest sounds good to me! 👍 

I'm just not sure about this one:
> Possibly convert single-document ports and even anyFileURI options to fileset + in-memory ports.

For very simple steps it may be overkill to use the fileset + in-memory model, as it would complicate their usage?

**Comment by bertfrees** [comment]
Yes you're probably right.
